#!D:\BCM5\DVC_CML\CI_CD_CT\End-to-end-Machine-Learning-Project-with-MLflow\env1\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
